ARDUINO_DIR = /usr/share/arduino
TARGET = boardcaster
BOARD_TAG = atmega328
ARDUINO_PORT = /dev/ttyUSB0

ARDUINO_LIBS = WiShield

AVR_TOOLS_PATH = /usr/bin

AVRDUDE_CONF     = /etc/avrdude.conf
include ../Arduino.mk
